version: '3.4'

services:
  http:
    build: .
    ports:
      - "${HTTP_PORT:-4001}:4001"
    volumes:
      # override packaged /app for dev
      - .:/app
      # node_modules may not be platform compatible, use the container's.
      - node_modules:/app/node_modules

volumes:
  node_modules:
